### ISSUE TITLE
Radiation drains current health

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#104]
When a kerbal receives radiation, their HP is reduced accordingly.

**Comment by theonegalen** [comment]
Does that not happen in the current version? I thought it did.

**Comment by GarwelGarwel** [comment]
Currently, radiation only affects maximum HP, but not current HP. It makes little difference as it is very, very slow anyway, but with the radiation storms mechanic it will become important.
