### ISSUE TITLE
Unexpected stats for certain SSPXR modules

### ISSUE THREAD

**Issue by LouisB3** [GarwelGarwel/KerbalHealth#114]
While reviewing the health modules in Stockalike Station Parts Expanded Redux, I noticed a number of values that seemed potentially out of place. Some of these may be intentional, but here are all of the stats that I noticed:

- The 3.75m lab provides a multiplier to the Connected factor for only 3 kerbals, less than the stock lab which provides the same multiplier for 4 kerbals. Based on the increase in crew capacity and mass compared to the stock lab, expected capacity for the multiplier would be about 5-6 kerbals.

- The 2.5m observation module seems to be a hybrid cupola/habitation module, providing recuperation and a hab multiplier at reduced efficacy for both. However, having a good value for either of these stats is way better than having a mediocre value for both. I suggest retooling this as a pure cupola since there are already many other habitat modules in SSPXR.

- The 3.7m "Asylum" radiation shelter has fairly modest built-in shielding (not sure if intentional, but see ChrisAdderley/StationPartsExpansionRedux#222). It also has very little living space (probably intentional); however, it has an extremely good multiplier to Confinement (10%), making it a super-effective hab (probably not intentional).

- The 1.25m centrifuges provide only modest multipliers to Microgravity (probably intentional, given their relatively low simulated gravity.) However, they also have very good multipliers to Confinement (10-20%), making them very good habitats (probably not intentional).

- The long rigid 2.5m hab has a better than typical Confinement multiplier (30% instead of the 40% that is common to the Hitchhiker and most other habitats).

- The 1.25m cupola provides a lot of living space for its low mass (see ChrisAdderley/StationPartsExpansionRedux#221).

**Comment by GarwelGarwel** [comment]
The first point will be fixed in the next release. The rest will have to wait for an overhaul of parts stats (especially of living space and confinement values) that I plan.

**Comment by GarwelGarwel** [comment]
All parts rebalanced for v1.5. Closing this issue. Reopen if anything is still outstanding.

**Comment by LouisB3** [comment]
Upon review of the stock and SSPXR values for KH 1.5.1, here is everything unexpected that I noticed. 

- Some parts have their lounge crew capacity explicitly defined, while others do not (I think this means they apply to everyone without limit). The parts without a defined lounge capacity are:
    - Stock:
        - Hitchhiker
        - Mk1 Cabin
        - Mk2 Cabin
        - Mk3 Cabin
    - SSPXR:
        - 1.25m habitat
        - 1.25m centrifuges (x2)
- The 3.75m radiation shelter, compared to the short 3.75m habitat, offers more space or a better confinement multiplier, but not better radiation shielding. It should be the reverse as it sacrifices habitable space for its resource tanks.
- Centrifuges have some unexpected or inconsistent features:
    - Unusually good confinement multipliers when used as a lounge (.16-.18, compared to .30 to .33 typically.)
    - No differentiation between sizes for the microgravity multiplier; previously, large rings provided better multipliers to correspond with their greater artificial gravity. (Crew capacity is a weaker differentiator as there is infrequently a reason to send more than a couple of kerbals anywhere.)
    - Microgravity crew capacity is specified for the 2.5m and 3.75m rings but not the 1.25m rings.
    - The 1.25m and 2.5m inflatable rings can hold radiation shielding, unlike other inflatables and the 3.75m centrifuges.
- Cupolas have lost their recuperation! This includes the 1.25m cupola, 2.5m observation module, and 3.75m cupola. (The 2.5m observation module also is still a lounge.)
- Medical bays have some inconsistency in their crew capacity. Per the patch notes, they should now provide vessel-wide benefits; however:
    - The stock MPL is still marked "partCrewOnly = true"
    - The 3.75m lab is marked "crewCap = 3"
