### ISSUE TITLE
NullReferenceException [mod: Deep Freeze]

### ISSUE THREAD

**Issue by NewTech32** [GarwelGarwel/KerbalHealth#122]
[Used Google Translate]
This mod is trying to calculate the radiation for a crew in freeze state, with a him ship ref = null.

I think how to solve this in [ _KerbalHealthStatus.cs_ ] you maybe need to swap two blocks in the lines:
* 1013 - _if (KerbalHealthRadiationSettings.Instance.RadiationEnabled) { ... }_
* 1034 - _if (frozen) { ... }_

=====================================================

[LOG 03:25:27.746] [KerbalHealth] Updating Билл Керман's health.
[LOG 03:25:27.746] [KerbalHealth] Vessel is null. No radiation added.
[EXC 03:25:27.748] NullReferenceException: Object reference not set to an instance of an object
	KerbalHealth.Core.DistanceToSun (Vessel v) (at <84bd5f57e15649559979a584b9f0d632>:0)
	KerbalHealth.KerbalHealthStatus.GetCosmicRadiation (Vessel v) (at <84bd5f57e15649559979a584b9f0d632>:0)
	KerbalHealth.KerbalHealthStatus.Update (System.Double interval) (at <84bd5f57e15649559979a584b9f0d632>:0)
	KerbalHealth.KerbalHealthList.Update (System.Double interval) (at <84bd5f57e15649559979a584b9f0d632>:0)
	KerbalHealth.KerbalHealthScenario.UpdateKerbals (System.Boolean forced) (at <84bd5f57e15649559979a584b9f0d632>:0)
	KerbalHealth.KerbalHealthScenario.FixedUpdate () (at <84bd5f57e15649559979a584b9f0d632>:0)

**Comment by GarwelGarwel** [comment]
Thanks, will take a look.

**Comment by GarwelGarwel** [comment]
Should be fixed by v1.5-pre

**Comment by GarwelGarwel** [comment]
Fixed in v1.5
