### ISSUE TITLE
Part type familiarity should have more direct effect

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#133]
Idea: instead of having familiarity with a part type double the training speed (which is rarely the bottleneck), it can provide a training level to start from, e.g. 50%. It will make familiarity a more important feature and encourage training kerbals even for vessels where they won't spend a lot of time.

**Comment by wile1411** [comment]
would tying the training level to the Kerbal level be an idea? Sort of a training % cap that depends on the level of the Kerbal and would still be a percentage of the max allowed depending on the Astronaut complex. Or would that be too annoying? 
eg  Kerbal can only train up to 
`KebalLvl/Training Cap		Astronaut ComplexLevel % reduction
				Lvl1	Lvl2	Lvl3
Lvl0 / 10%			6	7.5	8.5
Lvl1 / 30%			18	22.5	25.5
Lvl2 / 50%			30	37.5	42.5
Lvl3 / 70%			42	52.5	59.5
Lvl4 / 90%			54	67.5	76.5
Lvl5 / 100%			60	75	85`

**Comment by GarwelGarwel** [comment]
I considered using experience levels, but they already affect max HP in a big way, so this would make them OP.

**Comment by GarwelGarwel** [comment]
Another option is to streamline training a good deal: only train for part types, not specific parts. E.g., a kerbal trained for Mk1 Command Pod will handle well all vessels with this part. It will make the training system more transparent and clear (no need to remember which vessel is a clone of which etc.), but may be a bit bland. To compensate for it, more parts may be made trainable: engines, docking ports, wheels, legs and landing gear, scientific instruments, resource harvesters and converters etc.
