### ISSUE TITLE
Request: Toggle for decontamination requiring KSC

### ISSUE THREAD

**Issue by Violet754** [GarwelGarwel/KerbalHealth#135]
Hello! would it be possible to add a toggle to allow for decontaminations to be done offworld? with the current system many habitable planets in planet packs cannot be colonized long term.

**Comment by GarwelGarwel** [comment]
Technically, it's easy to do, but it will almost kill the whole idea of radiation as a soft limit on mission length.

And from a realism point of view, dealing with radiation is actually one of the big challenges of planetary colonization. You can use a lot of shielding (including some produced in-situ) to reduce exporure to almost 0. Or you can organize more or less regular "decontamination tours" to Kerbin for those who need it.

**Comment by Violet754** [comment]
yes it does remove the soft cap that radiation provides but on a habitable world with similar conditions to kerbin thats the point.
more configurability is always helpful although it is your mod and ultimately your choice how and if its done.

thank you for the consideration though!

**Comment by GarwelGarwel** [comment]
Implemented in the upcoming v1.6
