### ISSUE TITLE
DeepFreeze compatibility

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#14]
Allow freezed kerbals to maintain their health level infinitely.

**Comment by byaka** [comment]
https://github.com/PapaJoesSoup/RosterManager/tree/Dev
this branch have integration with new DeepFreeze's API, maybe it will help...

**Comment by GarwelGarwel** [comment]
Work on this feature is stalled due to DeepFreeze API issues. RPLRepo is aware of it, but I have no idea when (or whether) those issues are resolved. Meanwhile, I can make a quick and dirty fix (which will effectively just disable all health effects for kerbals inside freezers) if someone really needs it.

**Comment by byaka** [comment]
Bad news((( Can u pls link to issue here for tracing progress?

**Comment by GarwelGarwel** [comment]
https://github.com/JPLRepo/DeepFreeze/issues/71

**Comment by GarwelGarwel** [comment]
Idea: Use DF's GameEvents https://github.com/JPLRepo/DeepFreeze/blob/master/Source/APIs/DFGameEvents.cs
More info here: http://forum.kerbalspaceprogram.com/index.php?/topic/153112-ksp-122-gameevents-extension/

**Comment by GarwelGarwel** [comment]
Looks like it's done, at last!

**Comment by GarwelGarwel** [comment]
Assumed done.
