### ISSUE TITLE
Health Monitor sometimes shows details for wrong kerbal

### ISSUE THREAD

**Issue by LouisB3** [GarwelGarwel/KerbalHealth#140]
When there are enough kerbals in the space program to fill multiple pages of the Health Monitor window, sometimes clicking on the Details button for a kerbal will actually show the details for a kerbal on a different page. Closing and reopening the details window generally shows the details for the correct kerbal the second time.

Steps to reproduce:

- Start new sandbox game
- Recruit lots of kerbals
- Exit and reenter the savegame
- Go to Page 2 of the Health Monitor. Click on the Details button for the first kerbal listed. Observe that it opens the Health Details window for the first kerbal on Page 1 of the Health Monitor (probably Jebediah).
- Hit Back from the Health Details window, returning the Page 2 of the Health Monitor. Click on the Details button for the first kerbal on Page 2 again. This time it shows the Health Details for the expected kerbal.

**Comment by GarwelGarwel** [comment]
Fixed in v1.5.2.
