### ISSUE TITLE
can't decontaminate kerbals at KSC

### ISSUE THREAD

**Issue by tonimark** [GarwelGarwel/KerbalHealth#142]
as seen in this screenshot even with the right conditions kerbals seems to be unable to be decontaminated:
![20210103004954_1](https://user-images.githubusercontent.com/17166550/103468189-51878580-4d5f-11eb-9424-6f27980a60a2.jpg)

**Comment by wile1411** [comment]
What game mode is this in?

**Comment by tonimark** [comment]
oh sandbox, ok do you have any alternatives?

**Comment by GarwelGarwel** [comment]
Can you share your mod list and/or your save file (if you steel have this issue)?

**Comment by GarwelGarwel** [comment]
Will be fixed in v1.5.2.
