### ISSUE TITLE
exhausted and restored kerbal's inventories are cleared[1.11]

### ISSUE THREAD

**Issue by tonimark** [GarwelGarwel/KerbalHealth#143]
I found a bug in my space station, first I add some herbals with jetpack and cutes then they go exhausted then their health is restored and I found that they were empty 
REPRODUCE: 1.send kerbals with their inventory filled on the mission 
2.wait and get in kerbals exhausted and in a tourist state
3.bring kerbal's health back and back to their normal state
4.see the bug and the empty inventory

**Comment by GarwelGarwel** [comment]
Thanks for reporting this. I haven't played 1.11 yet, so it's helpful to know where to look. No ETA for a fix yet, but it will be the first thing I'll address.

**Comment by GarwelGarwel** [comment]
I tested it in KSP 1.11.2 and things look ok: kerbals get their stuff back after recuperating. Maybe it was a KSP issue fixed since then. I'm closing this report. Please reopen or start a new one if you encounter the problem again.
