### ISSUE TITLE
DeepFreeze conflict

### ISSUE THREAD

**Issue by Varep** [GarwelGarwel/KerbalHealth#144]
When i try to unfreeeze kerbal and then open health monitor it doesnt open. Even more: all GUI besides vessel parts doesnt react. Alt+F4 helps.

here is what consol says:
`[EXC 22:30:51.878] ArgumentException: An item with the same key has already been added. Key: Крылидон Керман
	System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <ad04dee02e7e4a85a1299c7ee81c79f6>:0)
	KerbalHealth.Core.KerbalVessel (ProtoCrewMember pcm) (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.Core.IsKerbalLoaded (ProtoCrewMember pcm) (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.KerbalHealthStatus.HealthChangePerDay () (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.KerbalHealthStatus.Update (System.Double interval) (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.KerbalHealthList.Update (System.Double interval) (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.KerbalHealthScenario.UpdateKerbals (System.Boolean forced) (at <8586019e4606488597329890625f82f0>:0)
	KerbalHealth.KerbalHealthScenario.FixedUpdate () (at <8586019e4606488597329890625f82f0>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

**Comment by GarwelGarwel** [comment]
Which versions of KSP and Kerbal Health do you use?

**Comment by Varep** [comment]
1.11.1.3066 KSP version and 1.3.8 Health

**Comment by Varep** [comment]
I used CKAN, now i see that there is 1.5.1 version. I ll try it

**Comment by Varep** [comment]
Ok. 1.5.1 works. Can u pls somehow update ur version in ckan?)
