### ISSUE TITLE
[1.12.1]confinement and microgravity are not calculated properly between loaded and unloaded vessels

### ISSUE THREAD

**Issue by tonimark** [GarwelGarwel/KerbalHealth#152]
I have seen a weird bug where kerbals on space station even when complete trained they would die out BUT when I am at the station with the complete loaded vessel the kerbals will be fine and also regenerate after I took 2 pictures I found that microgravity (since i had a gravity ring deployed from kerbalism mod) was -1.00 instead of the -0.39 on the space station and also confinement was -0.44 on earth and -0.10 on earth. these small differences can make kerbals work on the space station or die completely 
![KSC](https://user-images.githubusercontent.com/17166550/140533321-de79a69a-add8-473e-85e6-c5227809fa82.png)
![space station](https://user-images.githubusercontent.com/17166550/140533328-875cf9f6-6d9e-4df6-bd23-6a34a5479181.png)
kerbal health versions 1.5.5

**Comment by GarwelGarwel** [comment]
Fixed in #153
