### ISSUE TITLE
Error in KHMKS.cfg File preventing configs being applied past the Salamander

### ISSUE THREAD

**Issue by shaman327** [GarwelGarwel/KerbalHealth#170]
I noticed while playing the Tundra medical modules were not getting the recuperation benefit. After a lot of tracing where the issue was I noticed there is an extra } in the configuration for the salamander.
@PART[SalamanderPod]:NEEDS[MKS]		
{		
	MODULE	
	{	
		name = ModuleKerbalHealth
		space = 1.5
		complexity = 1
	}	
	**{   <----This one**
	RESOURCE
	{
		name = RadiationShielding
		amount = 0
		maxAmount = 2
	}
}		

It causing everything past the salamander to be skipped.

**Comment by GarwelGarwel** [comment]
Fixed in v1.6.6
