### ISSUE TITLE
Make Station Science patch

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#18]
First should see if they really need it.

**Comment by byaka** [comment]
I love StationScience mod, but what integration u want?

**Comment by GarwelGarwel** [comment]
Frankly, I haven't played it yet, but I understand they have their own custom station parts. If any of them are supposed to be residential, I can give them health bonuses.

**Comment by byaka** [comment]
@GarwelGarwel , only residential module - orbital lab. It equal to stock MobileLab (ofcourse spicific for this mod) so i think it must have same level of bonuses. If u plan to add bonuses to stock lab, i write patch for orbital lab and test it.

**Comment by GarwelGarwel** [comment]
In this case, perhaps no patches are needed. The lab should not give any health bonuses because it doesn't provide any additional comfort. In fact, it might have some maluses for its inhabitans (with different toxic substances, radiation, etc.), but it would be too evil.

**Comment by byaka** [comment]
> but it would be too evil.
I love this idea! Also if u do this, i think this negative effects can depend of level and profession of kerbals.

And another thing: in my opinion, when lab enabled, it can give some positive health bonuses for scientists (or disable some global negative bonuses) because true-scientists love what they doing.

**Comment by GarwelGarwel** [comment]
After some consideration, I decided that integration with StationScience is not relevant. We may get back to it after I implement radiation mechanics, but for now, the issue is closed.
