### ISSUE TITLE
Low health alarm

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#24]
- A screen message should show up and warp stopped when a kerbal's health drops below a threshold
- The threshold can be set in the Settings
- Alarm doesn't repeat until the kerbal's health increases above the threshold and drops again

**Comment by byaka** [comment]
Also integration with kerbal alarm clock maybe solution. Example of integration you can see in mod https://github.com/TriggerAu/TransferWindowPlanner

**Comment by GarwelGarwel** [comment]
I don't think KAC integration is needed here. It should be fairly easy to implement on my own.

**Comment by byaka** [comment]
> I don't think KAC integration is needed here
Why not? Having alarms from all mods in one place it good practice...

**Comment by GarwelGarwel** [comment]
1. Ideally, you should plan your missions so that you'll (almost) never hear this alarm. It's more a reminder that you've probably missed something--or were unlucky.

2. Health often changes in complex ways. It is not only affected by the direct linear factors (which also change during the mission), but also by "marginal health change", which is non-linear. I can try to come up with a formula to calculate it, but it's not really high in my list. Things are made even more complicated by random events introduced in 0.5.0. So I don't think it's right to think of health as something simply ticking down at a steady pace. It's not like that in real world and I want the mod to be realistic.

**Comment by byaka** [comment]
> Ideally, you should plan your missions so that you'll (almost) never hear this alarm

Living in ideal world so boring! That's why i play with mod DangIt, so no ideal missions anymore ;)

**Comment by GarwelGarwel** [comment]
Yeah, now imagine if DangIt had a counter "Your next malfunction will happen in 2d 4:25".

**Comment by byaka** [comment]
if this notification will try to determinate this by MTBF value only, it will be very helpful... For now i do it manually myself for every launch and create alarm.

**Comment by GarwelGarwel** [comment]
In a random process, MTBF won't help you know when you are going to have the failure. If your MTBF is 10 days, the event may happen in 2 days or in 50 days with roughly same probability. So setting a timer for 10 days won't give you anything: the chance of having a failure on day 10 is the same as having a failure on day 1 or day 100 (at least this is how Kerbal Health works, not sure about DangIt).

**Comment by GarwelGarwel** [comment]
Implemented in 0.6.4.
