### ISSUE TITLE
Need 'per-save' ability to disable mod

### ISSUE THREAD

**Issue by byaka** [GarwelGarwel/KerbalHealth#28]
For example i want to use this mod only in campaign. But i also have sandboxed save, where i testing some specific cases.

Also another scenario - sometimes i need to disable TAC LS in my campaign because it cause problems with 'rescue' contracts. So when i near kerbal, that i need rescue (near 30km), i disable TAC LS, get kerbal to my ship and then enable it again. Not big deal. And if KerbalHealth in future will have some bugs or problems like this, it will be a good solution.

**Comment by GarwelGarwel** [comment]
This option will be available in the next release.

**Comment by GarwelGarwel** [comment]
Resolved in v0.5.0.
