### ISSUE TITLE
CxAerospace: Stations Parts Pack integration

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#34]
eX-R-S Activity Module
inflatable centrifuge from Porkjet's pack

**Comment by LouisB3** [comment]
FYI, the centrifuge from the Habitat Pack is known to cause game crashes, which limits the number of mods that offer microgravity-mitigating parts. SSTU has some nice looking centrifuges though

**Comment by grafvonzan** [comment]
It would be great to add some of the Health modules to the CxAerospace: Stations Parts Pack in general. The config modifications would be pretty easy, but I'm not sure of the balance you guys are going for.

**Comment by GarwelGarwel** [comment]
Since that mod hasn't been updated to KSP 1.4.x, I consider it abandoned and close this request. Let me know if I'm wrong.
