### ISSUE TITLE
Add radiation factor

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#40]
- May affect HP (as other factors) or slowly decrease max HP (needs #38 )
- Radiation level depends on vessel location: lower on planet surface (0 for homeworld), grows with altitude, in interplanetary space depends on distance from the sun
- Can be reduced by shielding (can use heat shields for the lack of specialized parts) or better (heavier) habitation
- Can be healed on Kerbin for $$$

**Comment by LouisB3** [comment]
Leaving a note here re: interaction with other mods... I believe Kerbalism includes a radiation sim, and Nertea is working on one as well.

**Comment by GarwelGarwel** [comment]
Yes, I know about Kerbalism; its system is rather complex and realistic. But to use it, one has to have Kerbalism installed; so it's either a mechanic that will only be available to a minority of users or I'll have to implement and maintain two independent radiation systems and balance them both. I'll have to look at what Nertea has, but right now I'm inclined to implement a much simplified system of my own.

**Comment by GarwelGarwel** [comment]
Implemented in next release.
