### ISSUE TITLE
Radiation cure

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#53]
Allow to cure radiation effects at KSC (for ever increasing amounts of funds) and/or in flight (with some very advanced parts).

**Comment by wile1411** [comment]
Suggestion to outright 'ground' Kerbals for a period of time (maybe 1 month/year) to cure of radiation sickness.
To make it a reducing effectiveness, add extra time for any subsequent radiation treatments. (2 cure would be 2 months/2 years)

**Comment by GarwelGarwel** [comment]
Another idea: cure radiation in exchange for lowering kerbal's experience by 1 star. Possibly require a 3-level Astronauts' Complex and/or an advanced tech.

Pros:
- players will have to think twice even if they have lots of funds and can afford to wait a lot of time
- it will be harder and harder to regain the lost experience level because the kerbal will have to visit more and more places
- there is a kind of balance between increasing max HP by fixing radiation and losing it with an experience level (i.e. it only makes sense to cure a kerbal if they have lost 10+ HP to radiation)

Cons:
- may be considered too costly and never used in practice
- not sure how hard it is to code it

**Comment by theonegalen** [comment]
It is certainly an interesting idea. Might encourage some of my favorite kerbals to continue as Prime crew even further on down the line.

**Comment by GarwelGarwel** [comment]
Currently implemented with a flat cost of funds and science (defined in the Settings) + temporary health reduction. I couldn't find a way to decrease kerbal's experience level.

To do:

- [ ] Confirmation dialog or detailed information about cost and duration of decontamination
- [ ] Find a better place for the Decontamination button
- [ ] Test everything in all game modes
