### ISSUE TITLE
NullRef in latest release

### ISSUE THREAD

**Issue by lOmicronl** [GarwelGarwel/KerbalHealth#65]
I've just downloaded Kerbal Health 1.1.0 today, as well as [Nertea's test release 2 of his work-in-progress Station Parts Expansion redo](https://forum.kerbalspaceprogram.com/index.php?/topic/47223-wip-nerts-dev-thread-current-sspx-redux-alphas/&page=92&tab=comments#comment-3266614). Both of these are installed in a fresh KSP 1.3.1 instance. No other mods except for them and their bundled dependencies.

Nertea's mod is obviously not finished, and [the KerbalHealth patch for it came from a helpful forum user](https://forum.kerbalspaceprogram.com/index.php?/topic/47223-wip-nerts-dev-thread-current-sspx-redux-alphas/&page=92&tab=comments#comment-3266904) and may or may not be entirely sound.

With that understanding, I still want to report the following error, in case it happens to help you squash a genuine bug.

Upon interacting with some of the habitation parts from Nertea's mod - particularly the inflatable ones, which can change from having no crew capacity to gaining significant crew capacity and life support features in flight - I had my log spammed with unbelievable amounts of null reference exceptions, all of them identical repetitions of the following:

`NullReferenceException: Object reference not set to an instance of an object`
`  at KerbalHealth.ConnectedFactor.ChangePerDay (.ProtoCrewMember pcm) [0x00000] in <filename unknown>:0 `
`  at KerbalHealth.KerbalHealthStatus.HealthChangePerDay () [0x00000] in <filename unknown>:0 `
`  at KerbalHealth.KerbalHealthStatus.Update (Double interval) [0x00000] in <filename unknown>:0 `
`  at KerbalHealth.KerbalHealthList.Update (Double interval) [0x00000] in <filename unknown>:0 `
`  at KerbalHealth.KerbalHealthScenario.UpdateKerbals (Boolean forced) [0x00000] in <filename unknown>:0 `
`  at KerbalHealth.KerbalHealthScenario.FixedUpdate () [0x00000] in <filename unknown>:0 `

Hope this helps you with your development! KerbalHealth is one of the most interesting takes on life support I've seen to date, and I've been with KSP since 0.22 =)

**Comment by GarwelGarwel** [comment]
Can you enable Debug mode (Difficulty Settings > Kerbal Health > General Settings tab) for at least 10 seconds and attach the output log?

**Comment by lOmicronl** [comment]
Did so, log file is here: https://www.dropbox.com/s/osr5ipgmw1gxvtt/output_log.zip?dl=0

Didn't get massive spam of the error this time, but it does still show up repeatedly. The game also froze on me with a persistent input lock while pressing Revert Flight.

**Comment by GarwelGarwel** [comment]
Do you have CommNet enabled in your game?

**Comment by lOmicronl** [comment]
It was a sandbox save with default settings, just intended to take a look at the new parts and the stats they feature. Let me start up KSP real quick... yes, "Enable Comm Network" is checked.

**Comment by GarwelGarwel** [comment]
I understand this was fixed in one of the previous releases.
