### ISSUE TITLE
Stock 0.625 m heatshield has (potential) rad shield, DRE one does not.

### ISSUE THREAD

**Issue by reseune** [GarwelGarwel/KerbalHealth#66]
As in the title. I recommend this change be added to the DRE configs (it is copied directly from the equivalent stock heat shield):

@PART[0625_Heatshield]
{
	MODULE
	{
		name = ModuleKerbalHealth
		shielding = 0.25
	}
	RESOURCE
	{
		name = RadiationShielding
		amount = 0
		maxAmount = 0.25
	}
}

**Comment by GarwelGarwel** [comment]
Done. Thanks for pointing out!
