### ISSUE TITLE
Quirks info

### ISSUE THREAD

**Issue by GarwelGarwel** [GarwelGarwel/KerbalHealth#76]
Display details of quirks. Options:

- "?" button next to quirks that opens a new window with details
- Tooltip
- Button to send a message with kerbal's quirks info
- KSPedia/help page with all quirks

**Comment by theonegalen** [comment]
Yes, please! I would love to have more information about all the quirks!

**Comment by GarwelGarwel** [comment]
Implemented in v1.6.6 (at last!)
