### ISSUE TITLE
ksp [1.7]kerbals don't die when they reach health 0

### ISSUE THREAD

**Issue by tonimark** [GarwelGarwel/KerbalHealth#77]
when the kerbal reach health 0% they don't die

**Comment by GarwelGarwel** [comment]
Have you checked that death is enabled in the Kerbal Health settings? Could you share a log?

**Comment by tonimark** [comment]
I updated to ksp 1.7 I will check the settings a functionality I also updated kerbal health

**Comment by tonimark** [comment]
ok issue fixed ! it seemed to be an incompatibility issue
