### ISSUE TITLE
Major Log spam

### ISSUE THREAD

**Issue by Tabris83** [GarwelGarwel/KerbalHealth#89]
KSP v 1.7.3
Kerbal Health v 1.3.6

[Logs](https://github.com/Tabris83/KSP-Shipyard/tree/master/Bug%20Reports/KerbalHealth)

getting serious log spam.
kerbal health window is throwing InvalidOperationException errors when trying to open it in flight

**Comment by GarwelGarwel** [comment]
Fixed in v1.3.7
